### Accept = format of the response
### Content-Type = format of request body

@URLShortener_HostAddress = https://localhost:7138/URLShortener

POST {{URLShortener_HostAddress}}
Content-Type: application/json
Accept: application/json
{
   "url": "https://www.netflix.com/"
}

### 
GET {{URLShortener_HostAddress}}/9

### Delete given short code
DELETE {{URLShortener_HostAddress}}/3

### Delete All
DELETE {{URLShortener_HostAddress}}

###
PUT {{URLShortener_HostAddress}}/8
Content-Type: application/json
Accept: application/json
{
   "url": "https://www.google.com"
}

###
GET {{URLShortener_HostAddress}}/9/stats